kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: eidas-demo-ingress
  annotations:
    nginx.ingress.kubernetes.io/ssl-passthrough: "false"
spec:
  ingressClassName: nginx
  rules:
    - host: {{.Values.eidas_demo.hostname}}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: eidas-demo-service
                port:
                  number: 80
