{{- if eq .Values.debug true }}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: eidas-middleware-debug-service
  name: eidas-middleware-debug-service
spec:
  ports:
    - name: debug
      nodePort: {{ .Values.eidas_middleware.port.debug.extern }}
      port: {{ .Values.eidas_middleware.port.debug.intern }}
      protocol: TCP
      targetPort: {{ .Values.eidas_middleware.port.debug.intern }}
  selector:
    app: eidas-middleware
  type: NodePort
{{- end}}