apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: eidas-middleware-config-map
  name: eidas-middleware-config-map
data:
  # the application.properties file and the log4j2.xml that are mounted into the container
  application.properties: |
    #############
    logging.file=/opt/eidas-middleware/configuration/eidas-middleware.log
    logging.level.de.governikus=DEBUG
    management.endpoint.info.enabled=true
    management.endpoints.enabled-by-default=false
    server.adminInterfacePort={{ .Values.eidas_middleware.port.admin_interface}}
    server.port={{ .Values.eidas_middleware.port.server}}
    server.ssl.enabled=false
    server.use-forward-headers=true
    spring.datasource.password={{ .Values.eidas_middleware.datapase_pw}}
    spring.datasource.url=jdbc\:h2\:/opt/eidas-middleware/database/{{ .Values.eidas_middleware.database}};DB_CLOSE_DELAY\=-1;DB_CLOSE_ON_EXIT\=FALSE
    spring.datasource.username={{ .Values.eidas_middleware.database_user}}
    #HSM
    hsm.type={{ .Values.eidas_middleware.hsm | default "NO_HSM" }}
    hsm.keys.delete=30
    hsm.keys.archive=false
    pkcs11.config=/opt/eidas-middleware/pkcs11/pkcs11.cfg
    pkcs11.passwd=123456
    #############
  password.properties: |
    admin.hashed.password= {{ .Values.eidas_middleware.hashed_password }}
  log4j2.xml: |
    <?xml version="1.0" encoding="UTF-8"?>
    <Configuration status="WARN">
        <Appenders>
            <Console name="Console" target="SYSTEM_OUT">
                <PatternLayout
                        pattern="%d{DATE} [%t] %-5level [%X{correlation-id}] [%t] %logger{36} (%F:%L) - %msg%n%throwable"
                />
            </Console>
        </Appenders>
        <Loggers>
            <Root level="info">
                <AppenderRef ref="Console"/>
            </Root>
        </Loggers>
    </Configuration>