debug: true
hsm: false

eidas_middleware:
  hostname:
    eumw: autent-eumw-release-ec.govkg.de
    admin_interface: autent-eumw-admin-release-ec.govkg.de
  port:
    server: 8443
    admin_interface: 8449
    debug:
      intern: 5005
      extern: 31850
  image: dev-docker.governikus.de/governikus/eidas-middleware-application
  tag: 3.0.0-RC6
  hashed_password: $2a$10$EIwUSRpSu/eQzbtOw2dhvOJ2N6PIbTCGMhp9kc1sxEI2AAhKi0LxK
  volume: eidas-middleware-db
  database: eidas-middleware-db
  datapase_pw: fallturm
  database_user: h2

eidas_demo:
  hostname: autent-eumw-demo-release-ec.govkg.de
  middleware_samlreceiverurl: https://autent-eumw-release-ec.govkg.de/eidas-middleware/RequestReceiver
  ports:
    server: 8080
    debug:
      intern: 5005
      extern: 31851
  image: dev-docker.governikus.de/governikus/eidas-demo-application
  tag: 3.0.0-RC6
  demo_decryption_keystore: ec-sign-enc.p12
  demo_decryption_alias: secp521_middleware_ec_head
  demo_decryption_pin: 123456
  middleware_signature_certificate: middleware_ec_release.cer
  demo_signature_keystore: ec-sign-enc.p12
  demo_signature_alias: secp521_middleware_ec_head
  demo_signature_pin: 123456
